// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phaneritic.Implementations.Models.Ledgering;

#nullable disable

namespace Phaneritic.Implementations.Migrations.Ledgering
{
    [DbContext(typeof(LedgeringContext))]
    [Migration("20260106185555_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ldgr")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("ActivityID")
                .StartsAt(10000L)
                .IncrementsBy(100);

            modelBuilder.Entity("Phaneritic.Implementations.Models.Ledgering.Activity", b =>
                {
                    b.Property<long>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("ActivityID"), "ActivityID");

                    b.Property<int>("AccessMechanismID")
                        .HasColumnType("int");

                    b.Property<long>("AccessSessionID")
                        .HasColumnType("bigint");

                    b.Property<int>("AccessorID")
                        .HasColumnType("int");

                    b.Property<string>("ActivityTypeKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<long>("DurationMicroSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("DurationMilliSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EntryCount")
                        .HasColumnType("int");

                    b.Property<int>("ExceptionEntryCount")
                        .HasColumnType("int");

                    b.Property<int>("InfoEntryCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("MethodKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<long>("OperationID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ActivityID");

                    b.HasIndex("ActivityTypeKey");

                    b.ToTable("Activities", "ldgr");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Ledgering.ActivityType", b =>
                {
                    b.Property<string>("ActivityTypeKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("ActivityTypeKey");

                    b.ToTable("ActivityTypes", "ldgr");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Ledgering.ExceptionEntry", b =>
                {
                    b.Property<long>("ActivityID")
                        .HasColumnType("bigint");

                    b.Property<int>("EntryIndex")
                        .HasColumnType("int");

                    b.Property<int>("AccessMechanismID")
                        .HasColumnType("int");

                    b.Property<long>("AccessSessionID")
                        .HasColumnType("bigint");

                    b.Property<int>("AccessorID")
                        .HasColumnType("int");

                    b.Property<string>("ActivityTypeKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ExceptionName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MethodKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<long>("OffsetMicroSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("OffsetMilliSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("OperationID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityID", "EntryIndex");

                    b.ToTable("ExceptionEntries", "ldgr");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Ledgering.InfoEntry", b =>
                {
                    b.Property<long>("ActivityID")
                        .HasColumnType("bigint");

                    b.Property<int>("EntryIndex")
                        .HasColumnType("int");

                    b.Property<string>("InfoEntryKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("AccessMechanismID")
                        .HasColumnType("int");

                    b.Property<long>("AccessSessionID")
                        .HasColumnType("bigint");

                    b.Property<int>("AccessorID")
                        .HasColumnType("int");

                    b.Property<string>("ActivityTypeKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("InfoEntryValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MethodKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<long>("OffsetMicroSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("OffsetMilliSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("OperationID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ActivityID", "EntryIndex", "InfoEntryKey");

                    b.ToTable("InfoEntries", "ldgr");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Ledgering.Activity", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Ledgering.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Ledgering.ExceptionEntry", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Ledgering.Activity", "Activity")
                        .WithMany("ExceptionEntries")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Ledgering.InfoEntry", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Ledgering.Activity", "Activity")
                        .WithMany("InfoEntries")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Ledgering.Activity", b =>
                {
                    b.Navigation("ExceptionEntries");

                    b.Navigation("InfoEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
