// -------------------------------------
// <auto-generated>
// Code generated by T4 template
// Do not change output directly – it will get lost
// </auto-generated>
// -------------------------------------
using Phaneritic.Interfaces;
using Phaneritic.Interfaces.LudCache;
// TODO: add more here
// TODO: add more here
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Phaneritic.Implementations.LudCache;

// define refreshers

public static class ImplementationsRefreshers_Registrations
{
    public static IServiceCollection AddImplementationsRefreshers(this IServiceCollection services)
    {
        return services;
    }
}
