// -------------------------------------
// <auto-generated>
// Code generated by T4 template
// Do not change output directly – it will get lost
// </auto-generated>
// -------------------------------------
using Phaneritic.Interfaces;
using Phaneritic.Interfaces.LudCache;
using Phaneritic.Interfaces.Operational;
using Phaneritic.Interfaces.Ledgering;
// TODO: add more here
using Phaneritic.Implementations.Models.Operational;
using Phaneritic.Implementations.Models.Ledgering;
// TODO: add more here
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Phaneritic.Implementations.LudCache;

// define refreshers
public class ProcessNodeTypeKeyRefresh(
    IOperationalContext tableContext, 
    IPackRecord<ProcessNodeType, ProcessNodeTypeDto> packer,
    ILudDictionary<ProcessNodeTypeKey, ProcessNodeTypeDto> cacheData
    ) : LudCacheRefresherBase<ProcessNodeTypeKey, ProcessNodeTypeDto, ProcessNodeType>(packer, cacheData)
{
    public override RefresherKey RefresherKey => new(nameof(ProcessNodeTypeKeyRefresh));

    protected override IEnumerable<ProcessNodeType> GetModels()
        => tableContext.ProcessNodeTypes
        .Include(_t => _t.OptionGroups)
        .AsNoTracking();

    protected override ProcessNodeTypeKey GetKey(ProcessNodeTypeDto dto)
        => dto.ProcessNodeTypeKey;
}

public class ProcessNodeKeyRefresh(
    IOperationalContext tableContext, 
    IPackRecord<ProcessNode, ProcessNodeDto> packer,
    ILudDictionary<ProcessNodeKey, ProcessNodeDto> cacheData
    ) : LudCacheRefresherBase<ProcessNodeKey, ProcessNodeDto, ProcessNode>(packer, cacheData)
{
    public override RefresherKey RefresherKey => new(nameof(ProcessNodeKeyRefresh));

    protected override IEnumerable<ProcessNode> GetModels()
        => tableContext.ProcessNodes
        .Include(_t => _t.Options)
        .AsNoTracking();

    protected override ProcessNodeKey GetKey(ProcessNodeDto dto)
        => dto.ProcessNodeKey;
}

public class OptionTypeKeyRefresh(
    IOperationalContext tableContext, 
    IPackRecord<OptionType, OptionTypeDto> packer,
    ILudDictionary<OptionTypeKey, OptionTypeDto> cacheData
    ) : LudCacheRefresherBase<OptionTypeKey, OptionTypeDto, OptionType>(packer, cacheData)
{
    public override RefresherKey RefresherKey => new(nameof(OptionTypeKeyRefresh));

    protected override IEnumerable<OptionType> GetModels()
        => tableContext.OptionTypes
        .Include(_t => _t.OptionGroups)
        .AsNoTracking();

    protected override OptionTypeKey GetKey(OptionTypeDto dto)
        => dto.OptionTypeKey;
}

public class OptionGroupKeyRefresh(
    IOperationalContext tableContext, 
    IPackRecord<OptionGroup, OptionGroupDto> packer,
    ILudDictionary<OptionGroupKey, OptionGroupDto> cacheData
    ) : LudCacheRefresherBase<OptionGroupKey, OptionGroupDto, OptionGroup>(packer, cacheData)
{
    public override RefresherKey RefresherKey => new(nameof(OptionGroupKeyRefresh));

    protected override IEnumerable<OptionGroup> GetModels()
        => tableContext.OptionGroups
        .Include(_t => _t.OptionTypes)
        .AsNoTracking();

    protected override OptionGroupKey GetKey(OptionGroupDto dto)
        => dto.OptionGroupKey;
}

public class AccessGroupKeyRefresh(
    IOperationalContext tableContext, 
    IPackRecord<AccessGroup, AccessGroupDto> packer,
    ILudDictionary<AccessGroupKey, AccessGroupDto> cacheData
    ) : LudCacheRefresherBase<AccessGroupKey, AccessGroupDto, AccessGroup>(packer, cacheData)
{
    public override RefresherKey RefresherKey => new(nameof(AccessGroupKeyRefresh));

    protected override IEnumerable<AccessGroup> GetModels()
        => tableContext.AccessGroups
        .Include(_t => _t.Methods)
        .AsNoTracking();

    protected override AccessGroupKey GetKey(AccessGroupDto dto)
        => dto.AccessGroupKey;
}

public class MethodKeyRefresh(
    IOperationalContext tableContext, 
    IPackRecord<Method, MethodDto> packer,
    ILudDictionary<MethodKey, MethodDto> cacheData
    ) : LudCacheRefresherBase<MethodKey, MethodDto, Method>(packer, cacheData)
{
    public override RefresherKey RefresherKey => new(nameof(MethodKeyRefresh));

    protected override IEnumerable<Method> GetModels()
        => tableContext.Methods
        .Include(_t => _t.AccessMechanismTypes)
        .AsNoTracking();

    protected override MethodKey GetKey(MethodDto dto)
        => dto.MethodKey;
}

public class AccessMechanismTypeKeyRefresh(
    IOperationalContext tableContext, 
    IPackRecord<AccessMechanismType, AccessMechanismTypeDto> packer,
    ILudDictionary<AccessMechanismTypeKey, AccessMechanismTypeDto> cacheData
    ) : LudCacheRefresherBase<AccessMechanismTypeKey, AccessMechanismTypeDto, AccessMechanismType>(packer, cacheData)
{
    public override RefresherKey RefresherKey => new(nameof(AccessMechanismTypeKeyRefresh));

    protected override IEnumerable<AccessMechanismType> GetModels()
        => tableContext.AccessMechanismTypes
        .AsNoTracking();

    protected override AccessMechanismTypeKey GetKey(AccessMechanismTypeDto dto)
        => dto.AccessMechanismTypeKey;
}

public class AccessMechanismKeyRefresh(
    IOperationalContext tableContext, 
    IPackRecord<AccessMechanism, AccessMechanismDto> packer,
    ILudDictionary<AccessMechanismKey, AccessMechanismDto> cacheData
    ) : LudCacheRefresherBase<AccessMechanismKey, AccessMechanismDto, AccessMechanism>(packer, cacheData)
{
    public override RefresherKey RefresherKey => new(nameof(AccessMechanismKeyRefresh));

    protected override IEnumerable<AccessMechanism> GetModels()
        => tableContext.AccessMechanisms
        .AsNoTracking();

    protected override AccessMechanismKey GetKey(AccessMechanismDto dto)
        => dto.AccessMechanismKey;
}

public class AccessMechanismIDRefresh(
    IOperationalContext tableContext, 
    IPackRecord<AccessMechanism, AccessMechanismDto> packer,
    ILudDictionary<AccessMechanismID, AccessMechanismDto> cacheData
    ) : LudCacheRefresherBase<AccessMechanismID, AccessMechanismDto, AccessMechanism>(packer, cacheData)
{
    public override RefresherKey RefresherKey => new(nameof(AccessMechanismIDRefresh));

    protected override IEnumerable<AccessMechanism> GetModels()
        => tableContext.AccessMechanisms
        .AsNoTracking();

    protected override AccessMechanismID GetKey(AccessMechanismDto dto)
        => dto.AccessMechanismID;
}

public class ActivityTypeKeyRefresh(
    ILedgeringContext tableContext, 
    IPackRecord<ActivityType, ActivityTypeDto> packer,
    ILudDictionary<ActivityTypeKey, ActivityTypeDto> cacheData
    ) : LudCacheRefresherBase<ActivityTypeKey, ActivityTypeDto, ActivityType>(packer, cacheData)
{
    public override RefresherKey RefresherKey => new(nameof(ActivityTypeKeyRefresh));

    protected override IEnumerable<ActivityType> GetModels()
        => tableContext.ActivityTypes
        .AsNoTracking();

    protected override ActivityTypeKey GetKey(ActivityTypeDto dto)
        => dto.ActivityTypeKey;
}


public static class ImplementationsRefreshers_Registrations
{
    public static IServiceCollection AddImplementationsRefreshers(this IServiceCollection services)
    {
        services.AddScoped<ILudCacheRefresher, ProcessNodeTypeKeyRefresh>();
        services.AddScoped<ILudCacheRefresher, ProcessNodeKeyRefresh>();
        services.AddScoped<ILudCacheRefresher, OptionTypeKeyRefresh>();
        services.AddScoped<ILudCacheRefresher, OptionGroupKeyRefresh>();
        services.AddScoped<ILudCacheRefresher, AccessGroupKeyRefresh>();
        services.AddScoped<ILudCacheRefresher, MethodKeyRefresh>();
        services.AddScoped<ILudCacheRefresher, AccessMechanismTypeKeyRefresh>();
        services.AddScoped<ILudCacheRefresher, AccessMechanismKeyRefresh>();
        services.AddScoped<ILudCacheRefresher, AccessMechanismIDRefresh>();
        services.AddScoped<ILudCacheRefresher, ActivityTypeKeyRefresh>();
        return services;
    }
}
