// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phaneritic.Implementations.Models.Operational;

#nullable disable

namespace Phaneritic.Implementations.Migrations.Operational
{
    [DbContext(typeof(OperationalContext))]
    [Migration("20260106185553_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("op")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("AccessMechanismID")
                .StartsAt(10000L)
                .IncrementsBy(10);

            modelBuilder.HasSequence("AccessorID")
                .StartsAt(10000L)
                .IncrementsBy(10);

            modelBuilder.HasSequence("AccessSessionID")
                .StartsAt(100000L)
                .IncrementsBy(100);

            modelBuilder.HasSequence("OperationID")
                .StartsAt(100000L)
                .IncrementsBy(100);

            modelBuilder.HasSequence("OperationLogID")
                .StartsAt(100000L)
                .IncrementsBy(100);

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessGroup", b =>
                {
                    b.Property<string>("AccessGroupKey")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("AccessGroupKey");

                    b.HasIndex("AccessGroupKey")
                        .IsUnique();

                    b.ToTable("AccessGroups", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessGroupMethod", b =>
                {
                    b.Property<string>("AccessGroupKey")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("MethodKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("AccessGroupKey", "MethodKey");

                    b.HasIndex("MethodKey");

                    b.ToTable("AccessGroupMethods", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessMechanism", b =>
                {
                    b.Property<int>("AccessMechanismID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("AccessMechanismID"), "AccessMechanismID");

                    b.Property<string>("AccessMechanismKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AccessMechanismTypeKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessNodeKey")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("AccessMechanismID");

                    b.HasIndex("AccessMechanismKey")
                        .IsUnique();

                    b.HasIndex("AccessMechanismTypeKey");

                    b.HasIndex("ProcessNodeKey");

                    b.ToTable("AccessMechanisms", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessMechanismType", b =>
                {
                    b.Property<string>("AccessMechanismTypeKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsPoolable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRoamingAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidatedIPAddress")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessNodeTypeKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("AccessMechanismTypeKey");

                    b.HasIndex("ProcessNodeTypeKey");

                    b.ToTable("AccessMechanismTypes", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessSession", b =>
                {
                    b.Property<long>("AccessSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("AccessSessionID"), "AccessSessionID");

                    b.Property<int>("AccessMechanismID")
                        .HasColumnType("int");

                    b.Property<int>("AccessorID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AccessSessionID");

                    b.HasIndex("AccessMechanismID");

                    b.HasIndex("AccessorID");

                    b.ToTable("AccessSessions", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.Accessor", b =>
                {
                    b.Property<int>("AccessorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("AccessorID"), "AccessorID");

                    b.Property<string>("AccessorKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AccessorTypeKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("AccessorID");

                    b.HasIndex("AccessorKey");

                    b.HasIndex("AccessorTypeKey");

                    b.ToTable("Accessors", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessorAccessGroup", b =>
                {
                    b.Property<int>("AccessorID")
                        .HasColumnType("int");

                    b.Property<string>("AccessGroupKey")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("AccessorID", "AccessGroupKey");

                    b.HasIndex("AccessGroupKey")
                        .IsUnique();

                    b.ToTable("AccessorAccessGroups", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessorCredential", b =>
                {
                    b.Property<int>("AccessorID")
                        .HasColumnType("int");

                    b.Property<string>("AccessorCredentialTypeKey")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CredentialValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("AccessorID", "AccessorCredentialTypeKey");

                    b.HasIndex("AccessorCredentialTypeKey");

                    b.ToTable("AccessorCredentials", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessorCredentialType", b =>
                {
                    b.Property<string>("AccessorCredentialTypeKey")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("AccessorCredentialTypeKey");

                    b.ToTable("AccessorCredentialTypes", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessorType", b =>
                {
                    b.Property<string>("AccessorTypeKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("AccessorTypeKey");

                    b.ToTable("AccessorTypes", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessorTypeAccessMechanismType", b =>
                {
                    b.Property<string>("AccessorTypeKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("AccessMechanismTypeKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("AccessorTypeKey", "AccessMechanismTypeKey");

                    b.HasIndex("AccessMechanismTypeKey");

                    b.ToTable("AccessorTypeAccessMechanismTypes", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessorTypeAccessorCredentialType", b =>
                {
                    b.Property<string>("AccessorTypeKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("AccessorCredentialTypeKey")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.HasKey("AccessorTypeKey", "AccessorCredentialTypeKey");

                    b.HasIndex("AccessorCredentialTypeKey");

                    b.ToTable("AccessorTypeAccessorCredentialTypes", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.Method", b =>
                {
                    b.Property<string>("MethodKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsTransient")
                        .HasColumnType("bit");

                    b.Property<bool>("StayWithAccessMechanism")
                        .HasColumnType("bit");

                    b.Property<bool>("StayWithAccessor")
                        .HasColumnType("bit");

                    b.HasKey("MethodKey");

                    b.ToTable("Methods", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.MethodAccessMechanismType", b =>
                {
                    b.Property<string>("MethodKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("AccessMechanismTypeKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("MethodKey", "AccessMechanismTypeKey");

                    b.HasIndex("AccessMechanismTypeKey");

                    b.ToTable("MethodAccessMechanismTypes", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.Operation", b =>
                {
                    b.Property<long>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("OperationID"), "OperationID");

                    b.Property<int>("AccessMechanismID")
                        .HasColumnType("int");

                    b.Property<long>("AccessSessionID")
                        .HasColumnType("bigint");

                    b.Property<int>("AccessorID")
                        .HasColumnType("int");

                    b.Property<string>("MethodKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OperationID");

                    b.HasIndex("AccessSessionID");

                    b.HasIndex("AccessorID");

                    b.HasIndex("MethodKey");

                    b.HasIndex("AccessMechanismID", "AccessorID");

                    b.ToTable("Operations", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.OperationLog", b =>
                {
                    b.Property<long>("OperationLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("OperationLogID"), "OperationLogID");

                    b.Property<int>("AccessMechanismID")
                        .HasColumnType("int");

                    b.Property<long>("AccessSessionID")
                        .HasColumnType("bigint");

                    b.Property<int>("AccessorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LogTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MethodKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<long?>("OperationID")
                        .HasColumnType("bigint");

                    b.HasKey("OperationLogID");

                    b.ToTable("OperationLogs", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.Option", b =>
                {
                    b.Property<string>("ProcessNodeKey")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("OptionTypeKey")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("ProcessNodeKey", "OptionTypeKey");

                    b.ToTable("Options", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.OptionGroup", b =>
                {
                    b.Property<string>("OptionGroupKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("OptionGroupKey");

                    b.ToTable("OptionGroups", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.OptionGroupOptionType", b =>
                {
                    b.Property<string>("OptionGroupKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("OptionTypeKey")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("OptionGroupKey", "OptionTypeKey");

                    b.HasIndex("OptionTypeKey");

                    b.ToTable("OptionGroupOptionTypes", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.OptionType", b =>
                {
                    b.Property<string>("OptionTypeKey")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("OptionTypeKey");

                    b.ToTable("OptionTypes", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.ProcessNode", b =>
                {
                    b.Property<string>("ProcessNodeKey")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParentNodeKey")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ProcessNodeTypeKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("ProcessNodeKey");

                    b.HasIndex("ParentNodeKey");

                    b.HasIndex("ProcessNodeTypeKey");

                    b.ToTable("ProcessNodes", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.ProcessNodeType", b =>
                {
                    b.Property<string>("ProcessNodeTypeKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("ProcessNodeTypeKey");

                    b.ToTable("ProcessNodeTypes", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.ProcessNodeTypeOptionGroup", b =>
                {
                    b.Property<string>("ProcessNodeTypeKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("OptionGroupKey")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("ProcessNodeTypeKey", "OptionGroupKey");

                    b.HasIndex("OptionGroupKey");

                    b.ToTable("ProcessNodeTypeOptionGroups", "op");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessGroupMethod", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessGroup", "AccessGroup")
                        .WithMany("Methods")
                        .HasForeignKey("AccessGroupKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.Method", "Method")
                        .WithMany()
                        .HasForeignKey("MethodKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessMechanism", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessMechanismType", "AccessMechanismType")
                        .WithMany()
                        .HasForeignKey("AccessMechanismTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.ProcessNode", "ProcessNode")
                        .WithMany()
                        .HasForeignKey("ProcessNodeKey");

                    b.Navigation("AccessMechanismType");

                    b.Navigation("ProcessNode");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessMechanismType", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.ProcessNodeType", "ProcessNodeType")
                        .WithMany()
                        .HasForeignKey("ProcessNodeTypeKey");

                    b.Navigation("ProcessNodeType");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessSession", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessMechanism", "AccessMechanism")
                        .WithMany()
                        .HasForeignKey("AccessMechanismID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.Accessor", "Accessor")
                        .WithMany()
                        .HasForeignKey("AccessorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessMechanism");

                    b.Navigation("Accessor");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.Accessor", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessorType", "AccessorType")
                        .WithMany()
                        .HasForeignKey("AccessorTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessorType");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessorAccessGroup", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessGroup", "AccessGroup")
                        .WithOne("AccessorAccessGroup")
                        .HasForeignKey("Phaneritic.Implementations.Models.Operational.AccessorAccessGroup", "AccessGroupKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.Accessor", "Accessor")
                        .WithMany("AccessGroups")
                        .HasForeignKey("AccessorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("Accessor");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessorCredential", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessorCredentialType", "AccessorCredentialType")
                        .WithMany()
                        .HasForeignKey("AccessorCredentialTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.Accessor", "Accessor")
                        .WithMany("Credentials")
                        .HasForeignKey("AccessorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessor");

                    b.Navigation("AccessorCredentialType");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessorTypeAccessMechanismType", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessMechanismType", "AccessMechanismType")
                        .WithMany("AccessorTypes")
                        .HasForeignKey("AccessMechanismTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessorType", "AccessorType")
                        .WithMany("AccessMechanismTypes")
                        .HasForeignKey("AccessorTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessMechanismType");

                    b.Navigation("AccessorType");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessorTypeAccessorCredentialType", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessorCredentialType", "AccessorCredentialType")
                        .WithMany()
                        .HasForeignKey("AccessorCredentialTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessorType", "AccessorType")
                        .WithMany("AccessorCredentialTypes")
                        .HasForeignKey("AccessorTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessorCredentialType");

                    b.Navigation("AccessorType");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.MethodAccessMechanismType", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessMechanismType", "AccessMechanismType")
                        .WithMany("Methods")
                        .HasForeignKey("AccessMechanismTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.Method", "Method")
                        .WithMany("AccessMechanismTypes")
                        .HasForeignKey("MethodKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessMechanismType");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.Operation", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessMechanism", "AccessMechanism")
                        .WithMany()
                        .HasForeignKey("AccessMechanismID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.AccessSession", "AccessSession")
                        .WithMany()
                        .HasForeignKey("AccessSessionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.Accessor", "Accessor")
                        .WithMany()
                        .HasForeignKey("AccessorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.Method", "Method")
                        .WithMany()
                        .HasForeignKey("MethodKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AccessMechanism");

                    b.Navigation("AccessSession");

                    b.Navigation("Accessor");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.Option", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.ProcessNode", null)
                        .WithMany("Options")
                        .HasForeignKey("ProcessNodeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.OptionGroupOptionType", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.OptionGroup", null)
                        .WithMany("OptionTypes")
                        .HasForeignKey("OptionGroupKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.OptionType", null)
                        .WithMany("OptionGroups")
                        .HasForeignKey("OptionTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.ProcessNode", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.ProcessNode", "ParentNode")
                        .WithMany()
                        .HasForeignKey("ParentNodeKey");

                    b.HasOne("Phaneritic.Implementations.Models.Operational.ProcessNodeType", "ProcessNodeType")
                        .WithMany()
                        .HasForeignKey("ProcessNodeTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentNode");

                    b.Navigation("ProcessNodeType");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.ProcessNodeTypeOptionGroup", b =>
                {
                    b.HasOne("Phaneritic.Implementations.Models.Operational.OptionGroup", "OptionGroup")
                        .WithMany()
                        .HasForeignKey("OptionGroupKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phaneritic.Implementations.Models.Operational.ProcessNodeType", "ProcessNodeType")
                        .WithMany("OptionGroups")
                        .HasForeignKey("ProcessNodeTypeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionGroup");

                    b.Navigation("ProcessNodeType");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessGroup", b =>
                {
                    b.Navigation("AccessorAccessGroup");

                    b.Navigation("Methods");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessMechanismType", b =>
                {
                    b.Navigation("AccessorTypes");

                    b.Navigation("Methods");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.Accessor", b =>
                {
                    b.Navigation("AccessGroups");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.AccessorType", b =>
                {
                    b.Navigation("AccessMechanismTypes");

                    b.Navigation("AccessorCredentialTypes");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.Method", b =>
                {
                    b.Navigation("AccessMechanismTypes");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.OptionGroup", b =>
                {
                    b.Navigation("OptionTypes");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.OptionType", b =>
                {
                    b.Navigation("OptionGroups");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.ProcessNode", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Phaneritic.Implementations.Models.Operational.ProcessNodeType", b =>
                {
                    b.Navigation("OptionGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
