// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phaneritic.Implementations.EF.TableCache;

#nullable disable

namespace Phaneritic.Implementations.EF.Migrations.Kernel
{
    [DbContext(typeof(TableFreshnessContext))]
    [Migration("20260225220440_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("krnl")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Phaneritic.Implementations.EF.TableCache.TableFreshness", b =>
                {
                    b.Property<string>("TableKey")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<byte[]>("ConcurrencyCheck")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TableKey");

                    b.ToTable("TableFreshness", "krnl");
                });
#pragma warning restore 612, 618
        }
    }
}
