/* Use SqlCmd mode in SSMS */
:setvar dbName "Phaneritic"

USE [master]
GO

alter database [$(dbName)] set single_user with rollback immediate

/****** Object:  Database [$(dbName)]    Script Date: 5/2/2024 4:42:23 PM ******/
DROP DATABASE [$(dbName)]
GO

USE [master]
GO

/****** Object:  Database [$(dbName)]    Script Date: 5/2/2024 4:42:17 PM ******/
CREATE DATABASE [$(dbName)]
 CONTAINMENT = NONE
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

ALTER DATABASE [$(dbName)] MODIFY FILE
( NAME = N'$(dbname)', SIZE = 16384KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
GO

ALTER DATABASE [$(dbName)] MODIFY FILE
( NAME = N'$(dbname)_log', SIZE = 16384KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [$(dbName)].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [$(dbName)] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [$(dbName)] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [$(dbName)] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [$(dbName)] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [$(dbName)] SET ARITHABORT OFF 
GO

ALTER DATABASE [$(dbName)] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [$(dbName)] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [$(dbName)] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [$(dbName)] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [$(dbName)] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [$(dbName)] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [$(dbName)] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [$(dbName)] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [$(dbName)] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [$(dbName)] SET  DISABLE_BROKER 
GO

ALTER DATABASE [$(dbName)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [$(dbName)] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [$(dbName)] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [$(dbName)] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [$(dbName)] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [$(dbName)] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [$(dbName)] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [$(dbName)] SET RECOVERY FULL 
GO

ALTER DATABASE [$(dbName)] SET  MULTI_USER 
GO

ALTER DATABASE [$(dbName)] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [$(dbName)] SET DB_CHAINING OFF 
GO

ALTER DATABASE [$(dbName)] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [$(dbName)] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [$(dbName)] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [$(dbName)] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [$(dbName)] SET QUERY_STORE = ON
GO

ALTER DATABASE [$(dbName)] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [$(dbName)] SET  READ_WRITE 
GO

USE [$(dbName)]
GO
CREATE USER Phaneritic FOR LOGIN Phaneritic
GO
USE [$(dbName)]
GO
ALTER ROLE [db_owner] ADD MEMBER Phaneritic
GO
